version: 2

project_name: godotenv

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - DOCKER_CLI_EXPERIMENTAL=enabled

release:
  prerelease: auto
  draft: false
  github:
    owner: hoshsadiq
    name: godotenv

snapshot:
  version_template: "{{ incpatch .Version }}-next+{{ .ShortCommit }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

signs:
  - cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"

docker_signs:
  - cmd: cosign
    artifacts: manifests
    args:
      - "sign"
      - "${artifact}@${digest}"
      - "--yes"

builds:
  - id: godotenv
    main: ./cmd/godotenv
    binary: godotenv
    goos:
      - linux
      - darwin
      - freebsd
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - "6"
      - "7"

    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
      - -X 'main.gitCommit={{.ShortCommit}}'
      - -X 'main.projectName=godotenv'
      - -X 'main.projectURL=https://github.com/hoshsadiq/godotenv'

dockers_v2:
  - ids:
      - godotenv
    dockerfile: Dockerfile.goreleaser
    images:
      - ghcr.io/hoshsadiq/godotenv
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    annotations:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
